name: imc
version: 0.1.0.0
synopsis: Report on a Model Checker for Inquisitive Semantics
description: See report.pdf
maintainer: Bo Flachs & Wessel Kroon
category: Logic

ghc-options: -Wall

dependencies:
  - base >= 4.14 && < 5
  - random
  - QuickCheck

library:
  source-dirs: lib

tests:
  tests:
    main: tests.lhs
    source-dirs: test
    dependencies:
      - imc
      - QuickCheck
      - hspec
