name: imc
version: 0.1.0.0
synopsis: Report on a Model Checker for Inquisitive Semantics
description: See report.pdf
maintainer: Bo Flachs & Wessel Kroon
category: Logic

ghc-options: -Wall

dependencies:
  - base >= 4.14 && < 5
  - random

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - imc
